import type { ClientRole } from './roles';

export const PERMISSIONS = [
  'platform.overview.read',
  'platform.settings.manage',
  'platform.tenant.read',
  'platform.tenant.manage',
  'platform.channel.manage',
  'platform.ai.manage',
  'platform.reliability.read',
  'platform.reliability.manage',
  'platform.audit.read',
  'platform.access.manage',
  'platform.usage.read',
  'platform.billing.manage',
  'platform.payment.read',
  'platform.shipment.read',
  'tenant.profile.read',
  'tenant.profile.manage',
  'tenant.team.read',
  'tenant.team.manage',
  'channel.read',
  'channel.manage',
  'inbox.read',
  'inbox.manage',
  'conversation.read',
  'conversation.respond',
  'conversation.assign',
  'conversation.take_over',
  'contact.read',
  'contact.manage',
  'lead.read',
  'lead.manage',
  'knowledge.read',
  'knowledge.manage',
  'ai.settings.read',
  'ai.settings.manage',
  'booking.read',
  'booking.manage',
  'commerce.read',
  'commerce.manage',
  'payment.read',
  'payment.manage',
  'payment.approve',
  'shipment.read',
  'shipment.manage',
  'shipment.approve',
  'proof_of_delivery.read',
  'automation.read',
  'automation.manage',
  'automation.pause',
  'analytics.read',
  'analytics.export',
  'usage.read',
  'export.create',
  'event.publish',
  'inbox.dispatch',
  'outbox.dispatch',
  'media.process',
  'automation.execute',
  'analytics.aggregate',
] as const;

export type Permission = (typeof PERMISSIONS)[number];

const CLIENT_ROLE_PERMISSIONS = {
  CLIENT_OWNER: [
    'tenant.profile.read',
    'tenant.profile.manage',
    'tenant.team.read',
    'tenant.team.manage',
    'channel.read',
    'channel.manage',
    'inbox.read',
    'inbox.manage',
    'conversation.read',
    'conversation.respond',
    'conversation.assign',
    'conversation.take_over',
    'contact.read',
    'contact.manage',
    'lead.read',
    'lead.manage',
    'knowledge.read',
    'knowledge.manage',
    'ai.settings.read',
    'ai.settings.manage',
    'booking.read',
    'booking.manage',
    'commerce.read',
    'commerce.manage',
    'payment.read',
    'payment.manage',
    'payment.approve',
    'shipment.read',
    'shipment.manage',
    'shipment.approve',
    'proof_of_delivery.read',
    'automation.read',
    'automation.manage',
    'automation.pause',
    'analytics.read',
    'analytics.export',
    'usage.read',
    'export.create',
  ],
  CLIENT_ADMIN: [
    'tenant.profile.read',
    'tenant.profile.manage',
    'tenant.team.read',
    'tenant.team.manage',
    'channel.read',
    'channel.manage',
    'inbox.read',
    'inbox.manage',
    'conversation.read',
    'conversation.respond',
    'conversation.assign',
    'conversation.take_over',
    'contact.read',
    'contact.manage',
    'lead.read',
    'lead.manage',
    'knowledge.read',
    'knowledge.manage',
    'ai.settings.read',
    'ai.settings.manage',
    'booking.read',
    'booking.manage',
    'commerce.read',
    'commerce.manage',
    'payment.read',
    'payment.manage',
    'shipment.read',
    'shipment.manage',
    'proof_of_delivery.read',
    'automation.read',
    'automation.manage',
    'automation.pause',
    'analytics.read',
    'analytics.export',
    'usage.read',
    'export.create',
  ],
  CLIENT_MANAGER: [
    'tenant.profile.read',
    'tenant.team.read',
    'channel.read',
    'inbox.read',
    'inbox.manage',
    'conversation.read',
    'conversation.respond',
    'conversation.assign',
    'conversation.take_over',
    'contact.read',
    'contact.manage',
    'lead.read',
    'lead.manage',
    'knowledge.read',
    'ai.settings.read',
    'booking.read',
    'booking.manage',
    'commerce.read',
    'commerce.manage',
    'payment.read',
    'payment.approve',
    'shipment.read',
    'shipment.manage',
    'shipment.approve',
    'proof_of_delivery.read',
    'automation.read',
    'automation.pause',
    'analytics.read',
  ],
  CLIENT_AGENT: [
    'tenant.profile.read',
    'inbox.read',
    'conversation.read',
    'conversation.respond',
    'conversation.take_over',
    'contact.read',
    'contact.manage',
    'lead.read',
    'lead.manage',
    'knowledge.read',
    'booking.read',
    'booking.manage',
    'commerce.read',
    'commerce.manage',
    'payment.read',
    'shipment.read',
    'shipment.manage',
    'proof_of_delivery.read',
    'analytics.read',
  ],
  CLIENT_ANALYST: [
    'tenant.profile.read',
    'inbox.read',
    'conversation.read',
    'contact.read',
    'lead.read',
    'knowledge.read',
    'booking.read',
    'commerce.read',
    'payment.read',
    'shipment.read',
    'automation.read',
    'analytics.read',
    'analytics.export',
  ],
  CLIENT_VIEWER: [
    'tenant.profile.read',
    'inbox.read',
    'conversation.read',
    'lead.read',
    'knowledge.read',
    'booking.read',
    'commerce.read',
    'payment.read',
    'shipment.read',
    'automation.read',
    'analytics.read',
  ],
} as const satisfies Record<ClientRole, readonly Permission[]>;

export const PLATFORM_OWNER_PERMISSIONS = new Set<Permission>([
  'platform.overview.read',
  'platform.settings.manage',
  'platform.tenant.read',
  'platform.tenant.manage',
  'platform.channel.manage',
  'platform.ai.manage',
  'platform.reliability.read',
  'platform.reliability.manage',
  'platform.audit.read',
  'platform.access.manage',
  'platform.usage.read',
  'platform.billing.manage',
  'platform.payment.read',
  'platform.shipment.read',
]);

export const SERVICE_PERMISSIONS = new Set<Permission>([
  'event.publish',
  'inbox.dispatch',
  'outbox.dispatch',
  'media.process',
  'automation.execute',
  'analytics.aggregate',
]);

export function permissionsForRole(role: ClientRole): ReadonlySet<Permission> {
  return new Set(CLIENT_ROLE_PERMISSIONS[role]);
}

export function permissionAudience(
  permission: Permission,
): 'owner-console' | 'client-portal' | 'service' {
  if (permission.startsWith('platform.')) {
    return 'owner-console';
  }
  if (SERVICE_PERMISSIONS.has(permission)) {
    return 'service';
  }
  return 'client-portal';
}
